### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by D-Dennis** [uyjulian/krkrsdl2#7]
Hello, I have the same problem as https://github.com/uyjulian/krkrsdl2/issues/4.
When I try to build I get this Error: https://gist.github.com/D-Dennis/da0df5f2837417528e6ceb6d3e35ef65
Could you please help me?

**Comment by uyjulian** [comment]
I'll check it out

**Comment by uyjulian** [comment]
The build error has been fixed in Linux

**Comment by D-Dennis** [comment]
Thanks. The build works now. But when I execute it i get a Segmentation fault.
Here is a stack trace:
```
#0  FontSystem::ConstructDefaultFont (this=0x555555cb7d50)
    at ../external/krkrz/visual/FontSystem.cpp:53
No locals.
#1  FontSystem::ConstructDefaultFont (this=0x555555cb7d50)
    at ../external/krkrz/visual/FontSystem.cpp:47
No locals.
#2  FontSystem::FontSystem (this=0x555555cb7d50)
    at ../external/krkrz/visual/FontSystem.cpp:44
No locals.
#3  0x0000555555732968 in TVPInializeFontRasterizers ()
    at ../external/krkrz/visual/LayerBitmapImpl.cpp:84
No locals.
#4  0x0000555555776cbc in TVPCreateNativeClass_Font ()
    at ../external/krkrz/visual/LayerIntf.cpp:10311
        fontclass = <optimized out>
        fontclass = <optimized out>
#5  0x00005555556297f0 in TVPInitScriptEngine ()
    at ../external/krkrz/base/ScriptMgnIntf.cpp:205
        val = {<TJS::tTJSVariant_S> = {{Object = {Object = 0x555555cb0320, 
                ObjThis = 0x0}, Integer = 93824999949088, 
              Real = 4.6355709195901087e-310, String = 0x555555cb0320, 
              Octet = 0x555555cb0320}, vt = TJS::tvtObject}, <No data fields>}
        dsp = 0x555555cb0320
        global = 0x555555c87700
        waveclass = <optimized out>
        windowclass = <optimized out>
#6  0x00005555559d7a03 in tTVPApplication::StartApplication (
    this=0x555555c867c0, argc=<optimized out>, argv=<optimized out>)
    at ../src/core/environ/sdl2/Application.cpp:397
        engine_init = false
#7  0x00005555555cbc31 in main (argc=1, argv=0x7fffffffe118)
    at ../src/core/sdl2/SDLApplication.cpp:1435
```

**Comment by uyjulian** [comment]
fixed

**Comment by D-Dennis** [comment]
Still a Segmentation Fault:
```
#0  FontSystem::ConstructDefaultFont (this=0x555555cb7d50)
    at ../external/krkrz/visual/FontSystem.cpp:53
No locals.
#1  FontSystem::ConstructDefaultFont (this=0x555555cb7d50)
    at ../external/krkrz/visual/FontSystem.cpp:47
No locals.
#2  FontSystem::FontSystem (this=0x555555cb7d50)
    at ../external/krkrz/visual/FontSystem.cpp:44
No locals.
#3  0x0000555555732968 in TVPInializeFontRasterizers ()
    at ../external/krkrz/visual/LayerBitmapImpl.cpp:84
No locals.
#4  0x0000555555776cbc in TVPCreateNativeClass_Font ()
    at ../external/krkrz/visual/LayerIntf.cpp:10311
        fontclass = <optimized out>
        fontclass = <optimized out>
#5  0x00005555556297f0 in TVPInitScriptEngine ()
    at ../external/krkrz/base/ScriptMgnIntf.cpp:205
        val = {<TJS::tTJSVariant_S> = {{Object = {Object = 0x555555cb0320, 
                ObjThis = 0x0}, Integer = 93824999949088, 
              Real = 4.6355709195901087e-310, String = 0x555555cb0320, 
              Octet = 0x555555cb0320}, vt = TJS::tvtObject}, <No data fields>}
        dsp = 0x555555cb0320
        global = 0x555555c87700
        waveclass = <optimized out>
        windowclass = <optimized out>
#6  0x00005555559d7a03 in tTVPApplication::StartApplication (
    this=0x555555c867c0, argc=<optimized out>, argv=<optimized out>)
    at ../src/core/environ/sdl2/Application.cpp:397
        engine_init = false
#7  0x00005555555cbc31 in main (argc=1, argv=0x7fffffffe118)
    at ../src/core/sdl2/SDLApplication.cpp:1435
No locals.
#0  0x00007ffff7ab9b34 in pthread_getschedparam () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x0000555555701d2d in tTVPThread::SetPriority (
    this=this@entry=0x555555c85ab0, pri=pri@entry=ttpNormal)
    at /usr/include/c++/10.1.0/thread:197
        policy = -9296
        param = {sched_priority = 32767}
        err = <optimized out>
        maxpri = <optimized out>
        minpri = <optimized out>
        range = <optimized out>
        half = <optimized out>
#2  0x0000555555702daf in tTVPWatchThread::tTVPWatchThread (this=0x555555c85ab0)
    at ../external/krkrz/utils/TickCount.cpp:111
No locals.
#3  TVPWatchThreadInit () at ../external/krkrz/utils/TickCount.cpp:108
No locals.
#4  TVPGetTickCount () at ../external/krkrz/utils/TickCount.cpp:171
        curtick = <optimized out>
#5  0x00005555556310b8 in TVPRebuildAutoPathTable ()
    at ../external/krkrz/base/StorageIntf.cpp:1116
        cs_holder = <optimized out>
        tick = <optimized out>
        totalcount = <optimized out>
        it = <optimized out>
        endtick = <optimized out>
#6  0x0000555555632949 in TVPGetPlacedPath (name=...)
    at ../external/krkrz/base/StorageIntf.cpp:1281
        incache = 0x0
        cs_holder = {Section = 0x555555bcba00 <TVPCreateStreamCS>}
        normalized = {<TJS::tTJSString_S> = {
            Ptr = 0x7ffff78c8040}, <No data fields>}
        found = <optimized out>
        storagename = {<TJS::tTJSString_S> = {
            Ptr = 0x7ffff78c7b78}, <No data fields>}
        result = <optimized out>
#7  0x0000555555632d21 in TVPIsExistentStorage (name=...)
    at ../external/krkrz/base/StorageIntf.cpp:1347
No locals.
#8  0x00005555559d3047 in TVPInitializeBaseSystems ()
    at ../external/krkrz/tjs2/tjsString.h:102
        name_msgmap = u"msgmap.tjs"
        v = {<TJS::tTJSVariant_S> = {{Object = {Object = 0x31, 
                ObjThis = 0x7fffffffde70}, Integer = 49, 
              Real = 2.4209216646221081e-322, String = 0x31, Octet = 0x31}, 
            vt = TJS::tvtVoid}, <No data fields>}
        load_msgmap = true
#9  0x00005555559d7a9c in tTVPApplication::StartApplication (
    this=0x555555c867c0, argc=<optimized out>, argv=<optimized out>)
    at ../src/core/environ/sdl2/Application.cpp:404
        engine_init = true
#10 0x00005555555cbc51 in main (argc=1, argv=0x7fffffffe098)
    at ../src/core/sdl2/SDLApplication.cpp:1435
No locals.

```

**Comment by uyjulian** [comment]
Can't replicate

**Comment by D-Dennis** [comment]
I will try it in a Virtual MAchine with Ubuntu 18.04

**Comment by D-Dennis** [comment]
Works perfectly fine in the Virtual Machine. Thanks!
I'm running Arch Linux on my Host, I will try to figure out where the problem is.

**Comment by D-Dennis** [comment]
I was able to reproduce this bug on a manjaro linux x64 live cd https://manjaro.org/download/
Steps to reproduce:
- boot manjaro linux live cd
- then type following commands:
```
$ sudo pacman -Sy sdl2 meson base-devel # install dependecies
$ git clone https://github.com/uyjulian/krkrsdl2/
$ cd krkrsdl2
$ git submodule update --init --recursive
$ meson builddir
$ cd builddir
$ ninja
$ ./krkrsdl2
(info) Data path : file://./home/redacted/github/krkrsdl2/builddir/savedata/
----- CxImage Copyright START -----
CxImage version 7.0.2 07/Feb/2011
CxImage : Copyright (C) 2001 - 2011, Davide Pizzolato
Original CImage and CImageIterator implementation are:
Copyright (C) 1995, Alejandro Aguilar Sierra (asierra(at)servidor(dot)unam(dot)mx)
----- CxImage Copyright END -----

Program started on Linux (Linux)
[1]    32837 segmentation fault (core dumped)  ./krkrsdl2
```
Installed versions:
- sdl2 2.0.12-1
- meson 0.54.2-1
- make 4.3-3
- gcc 10.1.0-2
- glibc 2.31-5
- binutils 2.34-5
- bison 3.6.2-1
- m4 1.4.18-3
